export const category = [
  {
    title: "MEN",
    details: [
      {
        title: "SHOES",
        item: [
          "New Arrivals",
          "Originals",
          "Running",
          "Training",
          "Essentials",
          "Slides",
          "Golf",
          "Sportswear",
        ],
        summary: "All Men's Shoes",
      },
      {
        title: "CLOTHING",
        item: [
          "New Arrivals",
          "T-Shirts & Polo",
          "Jerseys",
          "Hoodies & Track Tops",
          "Sweatshirts",
          "Pants",
          "Tights",
          "Shorts",
          "Compression Layers",
          "Sportswear",
        ],
        summary: "All Men's Clothing",
      },
      {
        title: "ACCESSORIES",
        item: [
          "New Arrivals",
          "All Bags",
          "Backpacks",
          "Training Bags",
          "Socks",
          "Caps & Headwear",
          "Gloves",
          "Balls",
          "Face Cover",
        ],
        summary: "All Men's Accessories",
      },
      {
        title: "SALE",
        item: ["Shoes", "All Clothing", "Accessories"],
        summary: "All Men's",
      },
      {
        title: "SPORTS",
        item: [
          "Football",
          "Running",
          "Training",
          "Basketball",
          "Outdoor",
          "Swimming",
          "Golf",
        ],
        summary: "All Men's sports",
      },
    ],
  },
  {
    title: "WOMEN",
    details: [
      {
        title: "SHOES",
        item: [
          "New Arrivals",
          "Originals",
          "Running",
          "Training",
          "Essentials",
          "Slides",
          "Golf",
          "Sportswear",
        ],
        summary: "All Women's Shoes",
      },
      {
        title: "CLOTHING",
        item: [
          "New Arrivals",
          "T-Shirts & Tank Tops",
          "Sweatshirts and Tracksuits",
          "Sports Bras",
          "Jerseys",
          "Hoodies & Track Tops",
          "Jackets",
          "Pants",
          "Leggings",
          "Shorts",
          "Dresses",
          "Skirts",
          "Sportswear",
        ],
        summary: "All Women's Clothing",
      },
      {
        title: "ACCESSORIES",
        item: [
          "New Arrivals",
          "All Bags",
          "Backpacks",
          "Training Bags",
          "Socks",
          "Caps & Headwear",
          "Gloves",
          "Face Cover",
        ],
        summary: "All Women's Accessories",
      },
      {
        title: "SALE",
        item: ["Shoes", "All Clothing", "Accessories"],
        summary: "All Women's",
      },
      {
        title: "SPORTS",
        item: ["Running", "Training", "Yoga", "Golf", "Tennis", "Basketball"],
        summary: "All Women's sports",
      },
    ],
  },
  { title: "KIDS" },
  {
    title: "SPORTS",
    details: [
      {
        title: "FOOTBALL",
        item: [
          "Boots",
          "Clothing",
          "Accessories",
          "Predator",
          "X",
          "House of Jerseys",
        ],
        summary: "All Football",
      },
      {
        title: "RUNNING",
        item: ["Shoes", "Clothing", "Accessories"],
        summary: "All Running",
      },
      {
        title: "BASKETBALL",
        item: ["Shoes", "Clothing", "Accessories", "Basketball-Inspired"],
        summary: "All Basketball",
      },
      {
        title: "TRAINING",
        item: ["Shoes", "Clothing", "Accessories", "Heat RDY", "Essentials"],
        summary: "All Training",
      },
      {
        title: "OUTDOOR",
        item: ["Shoes", "Clothing"],
        summary: "All Outdoor",
      },
      {
        title: "OTHER SPORTS",
        item: ["Swimming", "Tennis", "Golf", "Cycling", "Yoga"],
      },
    ],
  },
  { title: "BRANDS" },
  { title: "NEW ARRIVALS" },
  { title: "TRENDING" },
];

export const footerCategory = [
  {
    title: "PRODUCTS",
    item: [
      "Shoes",
      "Apparel",
      "Accessories",
      "New Arrivals",
      "Release Dates",
      "Top Sellers",
      "Member exclusives",
      "Outlet",
    ],
  },
  {
    title: "SPORTS",
    item: [
      "Running",
      "Golf",
      "Football",
      "Basketball",
      "Tennis",
      "Gym & Training",
      "Outdoor",
      "Swimming",
      "Cycling",
    ],
  },
  {
    title: "COLLECTIONS",
    item: [
      "IVY PARK",
      "Ultraboost",
      "Pureboost",
      "Predator",
      "X",
      "Continental 80",
    ],
  },
  {
    title: "COMPANY INFO",
    item: ["About Us", "Careers", "Press"],
  },
  {
    title: "SUPPORT",
    item: [
      "Help",
      "Store Locator",
      "Size Charts",
      "Payment",
      "Delivery",
      "Returns & Refunds",
      "Promotions",
      "Sitemap",
    ],
  },
];
